package com.sod.quran.model;

public class SuratData {
    public static String[] juz={"Juz 1",
            "Juz 2",
            "Juz 3",
            "Juz 4",
            "Juz 5",
            "Juz 6",
            "Juz 7",
            "Juz 8",
            "Juz 9",
            "Juz 10" ,
            "Juz 11" ,
            "Juz 12",
            "Juz 13",
            "Juz 14",
            "Juz 15",
            "Juz 16",
            "Juz 17",
            "Juz 18",
            "Juz 19"   ,
            "Juz 20",
            "Juz 21",
            "Juz 22",
            "Juz 23",
            "Juz 24",
            "Juz 25",
            "Juz 26" ,
            "Juz 27",
            "Juz 28",
            "Juz 29" ,
            "Juz 30" };
    public static String[] juzDetail={"Surah Al-Faatiha 1:1 to Surah Al Baqarah 2:141",
            "Surah Al Baqarah 2:142 to Surah Al-Baqara 2:252",
            "Surah Al-Baqara 2:253 to Surah Aal-i-Imraan 3:92",
            "Surah Al-Imraan 3:93 to Surah An-Nisaa 4:23",
            "Surah An-Nisaa 4:24 to Surah An-Nisaa 4:147",
            "Surah An-Nisaa 4:148 to Surah Al-Maaida 5:81",
            "Surah Al-Maaida 5:83 to Surah Al-An'aam 6:110",
            "Surah Al-An'aam 6:111 to Surah Al-A'raaf 7:87",
            "Surah Al-A'raaf 7:88 to Surah Al-Anfaal 8:40",
            "Surah Al-Anfaal 8:41 to Surah At-Tawba 9:92",
            "Surah At-Tawba 9:93 to Surah Hud 11:5",
            "Surah Hud 11:6 to Surah Yusuf 12:52",
            "Surah Yusuf 12:53 to Surah Ibrahim 14:52",
            "Surah Al-Hijr 15:2 to Surah An-Nahl 16:128",
            "Surah Al-Israa 17:1 to Surah Al-Kahf 18:74",
            "Surah Al-Kahf 18:75 to Surah Taa-Haa 20:135",
            "Surah Al-Anbiyaa 21:21 to Surah Al-Hajj 22:78",
            "Surah Al-Muminoon 23:1 to Surah Al-Furqaan 25:20",
            "Surah Al-Furqaan 25:21 to Surah An-Naml 27:55",
            "Surah An-Naml 27:60 to Surah Al-Ankaboot 29:45",
            "Surah Al-Ankaboot 29:45 to Surah Al-Ahzaab 33:30",
            "Surah Al-Ahzaab 33:31 to Surah Yaseen 36:27",
            "Surah Yaseen 36:22 to Surah Az-Zumar 39:31",
            "Surah Az-Zumar 39:32 to Surah Fussilat 41:46",
            "Surah Fussilat 41:47 to Surah Al-Jaathiya 45:37" ,
            "Surah Al-Ahqaf 46:1 to Surah Adh-Dhaariyat 51:30",
            "Surah Adh-Dhaariyat 51:31 to Surah Al-Hadid 57:29",
            "Surah Al-Mujaadila 58:1 to Surah At-Tahrim 66:12",
            "Surah Al-Mulk 67:1 to Surah Al-Mursalaat 77:50",
            "Surah An-Naba 78:1 to Surah An-Naas 114:6"};
    public static String[] lang={"English - Ahmed Ali","English - Yusuf Ali" ,"Indonesia","Malay" };
    public static String[] size={"14 px","16 px" ,"18 px" ,"20 px"};
    public static String[] fontName={"lateef" ,"elmessiri" , "scheherazade"};
    public static String[] surat= {"Al-Fatihah", "Al-Baqarah", "Al-Imran", "An-Nisaa", "Al-Maidah", "Al-An'am", "Al-A'raf", "Al-Anfaal", "At-Taubah", "Yunus", "Huud", "Yusuf", "Ar-Ra'd", "Ibrahim", "Al-Hijr", "An-Nahl", "Al-Israa'", "Al-Kahfi", "Maryam", "Thaahaa", "Al-Anbiyaa", "Al-Hajj", "Al-Mu'minuun", "An-Nuur", "Al-Furqaan", "Asy-Syu'araa", "An-Naml", "Al-Qashash", "Al-'Ankabuut", "Ar-Ruum", "Luqman", "As-Sajdah", "Al-Ahzab", "Saba'", "Faathir", "YaaSiin", "Ash-Shaaffat", "Shaad", "Az-Zumar", "Al-Mu'min", "Fushshilat", "Asy-Syuura", "Az-Zukhruf", "Ad-Dukhaan", "Al-Jaatsiyah", "Al-Ahqaaf", "Muhammad", "Al-Fat-h", "Al-Hujuraat", "Qaaf", "Adz-Dzaariyat", "Ath-Thuur", "An-Najm", "Al-Qamar", "Ar-Rahmaan", "Al-Waaqi'ah", "Al-Hadiid", "Al-Mujaadilah", "Al-Hasyr", "Al-Mumtahanah", "Ash-Shaff", "Al-Jumuah", "Al-Munaafiqun", "At-Taghaabun", "Ath-Thalaaq", "At-Tahriim", "Al-Mulk", "Al-Qalam", "Al-Haaqqah", "Al-Ma'aarij", "Nuh", "Al-Jin", "Al-Muzzammil", "Al-Muddatstsir", "Al-Qiyaamah", "Al-Insaan", "Al-Mursalaat", "An-Naba'", "An-Naazi'aat", "'Abasa,42", "At-Takwiir", "Al-Infithaar", "Al-Muthaffif", "Al-Insyiqaaq", "Al-Buruuj", "Ath-Thaariq", "Al-A'laa", "Al-Ghaasyiyah", "Al-Fajr", "Al-Balad", "Asy-Syams", "Al-Lail", "Adh-Dhuhaa", "Al-Insyirah", "At-Tiin", "Al-'Alaq", "Al-Qadr", "Al-Bayyinah", "Az-Zalzalah", "Al-'Aadiyaat", "1Al-Qaari'ah", "At-Takaatsur", "Al-'Ashr", "Al-Humazah", "Al-Fiil", "Quraisy", "Al-Maa'uun", "Al-Kautsar", "Al-Kaafiruun", "An-Nashr", "Al-Lahab", "Al-Ikhlash", "Al-Falaq", "An-Naas"};


}
